### ISSUE TITLE
Discrepancy between README and sii_calculate.py

### ISSUE THREAD

**Issue by Staphylo** [liushilongbuaa/sonctsc#8]
While going over the code of `sii_calculate.py` I noticed a discrepancy with the `README`.

The `README` states:
 - `Summit Presentation Count	        Innovation	50`
 - `Hackathon Participation Team Count	Innovation	10`
 
However the `sii_calculate.py` uses:
 - `innovation_summit_presentation_count.json` -> `10 * count`
 - `innovation_hackathon_participation_team_count.json` -> `50 * count`

I feel the `README` makes more sense but feel free to resolve as needed.

**Comment by lihuay** [comment]
@liushilongbuaa : can you please take a look

**Comment by liushilongbuaa** [comment]
Thanks for point out that.
It is a mistake. I just fixed it. Score will auto updated in 1 hour.
